name: Playwright Tests
on:
  repository_dispatch:
    types: [run-tests]

jobs:
  run-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Notify initial repository
        run: |
          curl -X POST https://api.github.com/repos/sseung95/playwright-trigger-test/dispatches \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.INITIAL_REPO_TOKEN }}" \
            -d '{"event_type":"playwright-tests-completed", "client_payload": {"status": "${{ job.status }}"}}'
